server:
  port: 5080
spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - HEAD
                  - OPTIONS
          discovery:
            locator:
              enabled: true
          routes:
            - id: iti-service-auth
              uri: lb://ITI-SERVICE-AUTH
              predicates:
                - Path=/api/v1/auth/token,
                  /api/v1/auth/validate,
                  /iti-service-auth/swagger/**
            - id: iti-service-files
              uri: lb://ITI-SERVICE-FILES
              predicates:
                - Path=/api/v1/files,
                  /iti-service-files/swagger/**

logging:
  level:
    root: ${LOG_LEVEL:INFO}