spring:
  main:
    banner-mode: off
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - HEAD
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: iti-service-auth
          uri: lb://ITI-SERVICE-AUTH
          predicates:
            - Path=/api/v1/auth/token,
              /iti-service-auth/swagger/**

logging:
  level:
    root: ${LOG_LEVEL:DEBUG}